export const APP_INITIALIZE = 'APP_INITIALIZE';
export const APP_SOCKET_START = 'APP_SOCKET_START';
export const APP_SOCKET_MSG = 'APP_SOCKET_MSG';
export const APP_SOCKET_ERROR = 'APP_SOCKET_ERROR';
export const APP_SOCKET_OPEN = 'APP_SOCKET_OPEN';
export const APP_SOCKET_CLOSE = 'APP_SOCKET_CLOSE';
export const APP_SHUTDOWN = 'APP_SHUTDOWN';
export const APP_OPEN_CONTEXT_MENU = 'APP_OPEN_CONTEXT_MENU';
export const APP_CLOSE_CONTEXT_MENU = 'APP_CLOSE_CONTEXT_MENU';
export const APP_OPEN_CONFIRM = 'APP_OPEN_CONFIRM';
export const APP_CLOSE_CONFIRM = 'APP_CLOSE_CONFIRM';
export const APP_MODAL_MESSAGE_OPEN = 'APP_MODAL_MESSAGE_OPEN';
export const APP_MODAL_MESSAGE_CLOSE = 'APP_MODAL_MESSAGE_CLOSE';
export const APP_SET_DROPDOWN_ID = 'APP_SET_DROPDOWN_ID';
export const GET_STATUS_PAGE_INFO = 'GET_STATUS_PAGE_INFO';

export const SEARCH_SET_STRING = 'SEARCH_SET_STRING';
export const SEARCH_SET_TOKENS = 'SEARCH_SET_TOKENS';

export const ONBOARD_SET_REGION = 'ONBOARD_SET_REGION';
export const ONBOARD_GET_TEMPLATES = 'ONBOARD_GET_TEMPLATES';
export const ONBOARD_SET_CREDENTIALS = 'ONBOARD_SET_CREDENTIALS';
export const ONBOARD_SET_VPC = 'ONBOARD_SET_VPC';
export const ONBOARD_SET_SUBNET = 'ONBOARD_SET_SUBNET';
export const ONBOARD_SET_INSTALL_DATA = 'ONBOARD_SET_INSTALL_DATA';
export const ONBOARD_INSTALL = 'ONBOARD_INSTALL';
export const ONBOARD_EXAMPLE_INSTALL = 'ONBOARD_EXAMPLE_INSTALL';
export const ONBOARD_MAKE_LAUNCH_TEMPLATE = 'ONBOARD_MAKE_LAUNCH_TEMPLATE';
export const ONBOARD_SCAN_REGION = 'ONBOARD_SCAN_REGION';
export const ONBOARD_HAS_ROLE = 'ONBOARD_HAS_ROLE';
export const ONBOARD_GET_DEFAULT_NOTIFS = 'ONBOARD_GET_DEFAULT_NOTIFS';
export const ONBOARD_SET_DEFAULT_NOTIFS = 'ONBOARD_SET_DEFAULT_NOTIFS';
export const ONBOARD_SKIP_DEFAULT_NOTIFS = 'ONBOARD_SKIP_DEFAULT_NOTIFS';

export const USER_SIGNUP_CREATE = 'USER_SIGNUP_CREATE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REFRESH = 'USER_REFRESH';
export const USER_EDIT = 'USER_EDIT';
export const USER_GET_CUSTOMER = 'USER_GET_CUSTOMER';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_APPLY = 'USER_APPLY';
export const USER_GET_DATA = 'USER_GET_DATA';
export const USER_PUT_DATA = 'USER_PUT_DATA';
export const USER_SEND_RESET_EMAIL = 'USER_SEND_RESET_EMAIL';
export const USER_SEND_VERIFICATION_EMAIL = 'USER_SEND_VERIFICATION_EMAIL';
export const USER_SET_LOGIN_DATA = 'USER_SET_LOGIN_DATA';
export const USER_VERIFY_EMAIL = 'USER_VERIFY_EMAIL';

export const ENV_GET_ALL = 'ENV_GET_ALL';

export const GET_GROUP_SECURITY = 'GET_GROUP_SECURITY';
export const GET_GROUPS_SECURITY = 'GET_GROUPS_SECURITY';
export const GET_GROUP_ASG = 'GET_GROUP_ASG';
export const GET_GROUPS_ASG = 'GET_GROUPS_ASG';
export const GET_GROUP_RDS = 'GET_GROUP_RDS';
export const GET_GROUPS_RDS = 'GET_GROUPS_RDS';
export const GET_GROUP_ELB = 'GET_GROUP_ELB';
export const GET_GROUPS_ELB = 'GET_GROUPS_ELB';

export const GET_INSTANCE_ECC = 'GET_INSTANCE_ECC';
export const GET_INSTANCES_ECC = 'GET_INSTANCES_ECC';
export const GET_INSTANCE_RDS = 'GET_INSTANCE_RDS';
export const GET_INSTANCES_RDS = 'GET_INSTANCES_RDS';

export const GET_METRIC_RDS = 'GET_METRIC_RDS';

export const ENV_GET_BASTIONS = 'ENV_GET_BASTIONS';
export const ENV_SET_FILTERED = 'ENV_SET_FILTERED';
export const ENV_SELECT_TOGGLE = 'ENV_SELECT_TOGGLE';
export const FILTER_ENV = 'FILTER_ENV';

export const GET_CHECK = 'GET_CHECK';
export const GET_CHECK_FROM_S3 = 'GET_CHECK_FROM_S3';
export const GET_CHECKS = 'GET_CHECKS';
export const GET_CHECKS_NOTIFICATIONS = 'GET_CHECKS_NOTIFICATIONS';
export const CHECK_CREATE = 'CHECK_CREATE';
export const CHECK_EDIT = 'CHECK_EDIT';
export const CHECK_CREATE_OR_EDIT = 'CHECK_CREATE_OR_EDIT';
export const CHECKS_DELETE_PENDING = 'CHECKS_DELETE_PENDING';
export const CHECKS_DELETE = 'CHECKS_DELETE';
export const CHECK_TEST = 'CHECK_TEST';
export const CHECK_TEST_RESET = 'CHECK_TEST_RESET';
export const CHECK_TEST_SELECT_RESPONSE = 'CHECK_TEST_SELECT_RESPONSE';
export const CHECKS_SET_FILTERED = 'CHECKS_SET_FILTERED';
export const CHECK_SELECT_TOGGLE = 'CHECK_SELECT_TOGGLE';
export const CHECK_MULTIEDIT = 'CHECK_MULTIEDIT';

export const AWS_REBOOT_INSTANCES = 'AWS_REBOOT_INSTANCES';
export const AWS_START_INSTANCES = 'AWS_START_INSTANCES';
export const AWS_STOP_INSTANCES = 'AWS_STOP_INSTANCES';

export const INTEGRATIONS_EMAIL_TEST = 'INTEGRATIONS_EMAIL_TEST';
export const INTEGRATIONS_SLACK_INFO = 'INTEGRATIONS_SLACK_INFO';
export const INTEGRATIONS_SLACK_TEST = 'INTEGRATIONS_SLACK_TEST';
export const INTEGRATIONS_SLACK_ACCESS = 'INTEGRATIONS_SLACK_ACCESS';
export const INTEGRATIONS_SLACK_CHANNELS = 'INTEGRATIONS_SLACK_CHANNELS';

export const INTEGRATIONS_PAGERDUTY_INFO = 'INTEGRATIONS_PAGERDUTY_INFO';
export const INTEGRATIONS_PAGERDUTY_ACCESS = 'INTEGRATIONS_PAGERDUTY_ACCESS';
export const INTEGRATIONS_PAGERDUTY_TEST = 'INTEGRATIONS_PAGERDUTY_TEST';

export const ANALYTICS_EVENT = 'ANALYTICS_EVENT';
export const ANALYTICS_PAGEVIEW = 'ANALYTICS_PAGEVIEW';
export const ANALYTICS_USER_UPDATE = 'ANALYTICS_USER_UPDATE';
export const INTERCOM_SHOW = 'INTERCOM_SHOW';
export const INTERCOM_HIDE = 'INTERCOM_HIDE';