import _ from 'lodash';
import React, {PropTypes} from 'react';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import cx from 'classnames';

import {checks as actions} from '../../actions';
import Checkmark from './Checkmark';
import {Padding} from '../layout';
import {Button} from '../forms';
import style from './onboard.css';

const PostInstall = React.createClass({
  propTypes: {
    redux: PropTypes.shape({
      checks: PropTypes.object,
      app: PropTypes.shape({
        scheme: PropTypes.string
      })
    }),
    actions: PropTypes.shape({
      getChecks: PropTypes.func
    })
  },
  componentWillMount(){
    this.props.actions.getChecks();
  },
  getAutogeneratedCheckCount(){
    return this.props.redux.checks.checks.filter(check => {
      return _.endsWith(check.name, '(auto)');
    }).size;
  },
  renderCheckCount(){
    const numChecks = this.getAutogeneratedCheckCount();
    if (numChecks <= 0) {
      return null;
    }
    if (numChecks === 1) {
      return (
        <Padding t={3} b={1} className="text-center">
          <h2>{numChecks}</h2>
          <h3 style={{fontWeight: 300}}>health check</h3>
          <p>was created for you!</p>
        </Padding>
      );
    }
    return (
      <Padding t={3} b={1} className="text-center">
        <h2>{numChecks}</h2>
        <h3 style={{fontWeight: 300}}>health checks</h3>
        <p>were created for you!</p>
      </Padding>
    );
  },
  render(){
    return (
      <div className={cx(style.transitionPanel, style[this.props.redux.app.scheme])}>
        <Padding t={4} b={1} lr={2} style={{margin: '0 auto'}}>
          <Checkmark />
        </Padding>
        <div className="text-center">
          <h2>You&rsquo;re all done!</h2>
          <p>The Opsee instance was successfully installed.</p>
        </div>
        {this.renderCheckCount()}
        <Padding t={2} b={2}>
          <Button to="/" color="success" block chevron>Check them out</Button>
        </Padding>
      </div>
    );
  }
});

const mapStateToProps = (state) => ({
  redux: state
});

const mapDispatchToProps = (dispatch) => ({
  actions: bindActionCreators(actions, dispatch)
});

export default connect(mapStateToProps, mapDispatchToProps)(PostInstall);